# Config file for automatic testing at travis-ci.org

sudo: false
language: python
dist: xenial
matrix:
    include:
      - python: '3.4'
        env: TOXENV=py34
      - python: '3.5'
        env: TOXENV=py35
      - python: '3.6'
        env: TOXENV=py36
      - python: '3.7'
        env: TOXENV=py37
      - python: 'pypy3.5-6.0'
        env: TOXENV=pypy3
      - python: '3.7'
        env: TOXENV=linting

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools tox

script:
  - tox

cache:
    directories:
        - $HOME/.cache/pre-commit
