# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python34"
      TOXENV: "py34"

    - PYTHON: "C:\\Python35"
      TOXENV: "py35"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

    - PYTHON: "C:\\Python37"
      TOXENV: "py37"

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install tox"
  - "%PYTHON%/Scripts/pip install wheel"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox"
